module Message
  SUCCESS = 'SUCCESS'
  FAILURE = 'FAILURE'
  HOUSEFUL = 'HOUSEFUL'
  MEMBER_NOT_FOUND = 'MEMBER_NOT_FOUND'
  INCORRECT_PAYMENT = 'INCORRECT_PAYMENT'
  INVALID_COMMAND = 'INVALID_COMMAND!'
  NOT_IMPLEMENTED = 'NOT_IMPLEMENTED'
  INSUFFICIENT_PARAMS = 'INSUFFICIENT_PARAMS'
end

module Commands
  MOVE_IN = 'MOVE_IN'
  MOVE_OUT = 'MOVE_OUT'
  CLEAR_DUE = 'CLEAR_DUE'
  SPEND = 'SPEND'
  DUES = 'DUES'
end
